---
title: "SiRCle tutorial R"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{SiRCle tutorial R}
  %\VignetteEncoding{UTF-8}
---

## Install the R package

```{r}
#install.packages("devtools")
library(devtools)
install_github("ArianeMora/SiRCleR_M1")
library(sircleM1)
```

### SiRCle tutorial in R

Note we assume your methylation CpGs map to a single gene, if they don't  you'll need to filter them.

```{r}
#install.packages('BiocManager')
#BiocManager::install('basilisk')
library(basilisk)
# Set this to be the path to the example data we downloaded
data_dir <- '../data_example/'

protFile <- paste0(data_dir, 'prot_DE_Stage IV_sircle.csv')
rnaFile <- paste0(data_dir, 'rna_DE_Stage IV_sircle_renamed-cols.csv')
methFile <- paste0(data_dir, 'filtered_cpg_DE_Stage IV_sircle.csv')
geneId <- 'ensembl_gene_id'

sircleFileName <- paste0(data_dir, "SircleR-RCM.csv")

# Use basilisk to create an environment we can use
bas_scircm <- BasiliskEnvironment(envname="s_sircle",
                                   pkgname="sircle",
                                   packages=c("numpy==1.20"),
                                  pip=c("sircle==0.0.2")
)



#logFC_rna = column name in your RNA file that has your RNA logFC (same for the protein and CpG)
#padj_rna = column name in your RNA file that has your padj value (same for protein and CpG)
#NOTE: these need to be unique from one another since we merge the datasets, if they aren't, you need
#to update your csv files.
#Lastly: ensembl_gene_id this is the gene ID column, All must use the same identifier, and this must be
#labelled the same in each file, if it isn't, update your column names before running.
res <- basiliskRun(env=bas_scircm, fun=function(args) {
    rcm <- sircleM1::sircleRCM(rnaFile, methFile, protFile, geneId,  "logFC_rna", "padj_rna", "CpG_Beta_diff", "padj_meth", "logFC_protein", "padj_protein",
                 outputFileName = sircleFileName, 
                 envName="s_sircle")
    # Do something with pandas
    return(rcm)
})


# Plot the sircle function
sirclePlot(sircleFileName, regLabels="Regulation_Grouping_2") 

# Note you need the following packages installed for the ORA:
# "org.Hs.eg.db", "clusterProfiler", "svglite", "enrichplot"
# Run ORA on the groups
sircleORAHuman(sircleFileName, "entrezgene_id", "Regulation_Grouping_2")

```


### TF analysis using Dorothea


# TF analysis
```{r}
doroFile <- paste0(data_dir, 'dorothea_hs_ABCD.csv')
TFPadjCol <- 'padj_rna'
TFValueCol <- 'logFC_rna'
TargetPadjCol <- 'padj_rna'
TargetValueCol <- 'logFC_rna'
outputDir <- data_dir
clusterGeneId <- "external_gene_name" # This has to match the gene names in doro file
m_df <- sircleMotif(clusterGeneId, doroFile, sircleFileName, TFPadjCol, TFValueCol, TargetPadjCol, TargetValueCol, "Regulation_Grouping_2",
                     doroLevel=c("A"), clusters=c("TMDE", "TMDS", "MDS", "MDE", "TPDE", "TPDS"), TFInDataset=F, outputDir='.', plotOn=T)
```



